service: lbd-answer-report

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  iam:
    role: arn:aws:iam::303732912389:role/lambda-role

functions:
  answerReport:
    handler: handler.answerReport
